# Generated by Django 3.0.5 on 2020-04-28 03:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200423_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 28, 3, 35, 1, 637061, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timezone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
